import turtle as trtl

painter = trtl.Turtle()

painter.turtlesize(3)
painter.pensize(5)

painter.pencolor("grey")
painter.circle(100)
painter.penup()
painter.goto(-140, 80)
painter.pendown()
painter.pencolor("black")
painter.circle(40)
painter.penup()
painter.goto(0, 0)
painter.pendown()
painter.setheading(270)
painter.forward(50)
painter.setheading(180)
painter.forward(15)
painter.setheading(90)
painter.forward(53)
painter.backward(53)
painter.setheading(180)
painter.penup()
painter.forward(10)
painter.pendown()
painter.setheading(90)
painter.forward(54)
painter.backward(54)
painter.setheading(180)
painter.forward(15)
painter.setheading(90)
painter.forward(60)

painter.penup()
painter.goto(0, 0)
painter.setheading(0)
painter.forward(10)
painter.pendown()
painter.setheading(270)
painter.forward(50)
painter.setheading(0)
painter.forward(15)
painter.setheading(90)
painter.forward(53)
painter.backward(53)
painter.setheading(0)
painter.penup()
painter.forward(10)
painter.pendown()
painter.setheading(90)
painter.forward(54)
painter.backward(54)
painter.setheading(0)
painter.forward(15)
painter.setheading(90)
painter.forward(60)


wn = trtl.Screen()
wn.mainloop()