import turtle as trtl

painter = trtl.Turtle()

painter.penup()
painter.goto(-500,350)
painter.pendown()
painter.turtlesize(3)
painter.pensize(30)

painter.pencolor("red")
painter.setheading(0)
painter.forward(1000)
painter.setheading(270)
painter.forward(30)
painter.setheading(180)
painter.forward(1000)
painter.setheading(90)
painter.forward(30)
painter.backward(60)
painter.setheading(0)
painter.forward(1000)
painter.setheading(90)
painter.forward(30)
painter.penup()
painter.backward(60)
painter.pendown()

painter.pencolor("orange")
painter.setheading(180)
painter.forward(1000)
painter.setheading(270)
painter.forward(30)
painter.setheading(0)
painter.forward(1000)
painter.setheading(90)
painter.forward(30)
painter.backward(60)
painter.setheading(180)
painter.forward(1000)
painter.setheading(90)
painter.forward(30)
painter.penup()
painter.backward(60)
painter.pendown()

painter.pencolor("yellow")
painter.setheading(0)
painter.forward(1000)
painter.setheading(270)
painter.forward(30)
painter.setheading(180)
painter.forward(1000)
painter.setheading(90)
painter.forward(30)
painter.backward(60)
painter.setheading(0)
painter.forward(1000)
painter.setheading(90)
painter.forward(30)
painter.penup()
painter.backward(60)
painter.pendown()

painter.pencolor("green")
painter.setheading(180)
painter.forward(1000)
painter.setheading(270)
painter.forward(30)
painter.setheading(0)
painter.forward(1000)
painter.setheading(90)
painter.forward(30)
painter.backward(60)
painter.setheading(180)
painter.forward(1000)
painter.setheading(90)
painter.forward(30)
painter.penup()
painter.backward(60)
painter.pendown()

painter.pencolor("blue")
painter.setheading(0)
painter.forward(1000)
painter.setheading(270)
painter.forward(30)
painter.setheading(180)
painter.forward(1000)
painter.setheading(90)
painter.forward(30)
painter.backward(60)
painter.setheading(0)
painter.forward(1000)
painter.setheading(90)
painter.forward(30)
painter.penup()
painter.backward(60)
painter.pendown()

painter.pencolor("violet")
painter.setheading(180)
painter.forward(1000)
painter.setheading(270)
painter.forward(30)
painter.setheading(0)
painter.forward(1000)
painter.setheading(90)
painter.forward(30)
painter.backward(60)
painter.setheading(180)
painter.forward(1000)
painter.setheading(90)
painter.forward(30)
painter.penup()
painter.backward(60)
painter.pendown()


wn = trtl.Screen()
wn.mainloop()
